### PR TITLE
Texts

### PR DESCRIPTION
**Pull request by dguzenko**

### CODE REVIEW

**Comment by miljan-aleksic** [comment]
I don't see the old docs were deleted

**Comment by dguzenko** [comment]
I didn't delete them, but just hid, deleting from menu. You told me do so :) 
Am I wrong?

**Comment by miljan-aleksic** [comment]
That's ok, but fi we have the whole content in one new doc, there is no need to keep the old ones. Delete them :)

**Comment by dguzenko** [comment]
Done

**Pull request merged**
